apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hackernews-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hn
    spec:
      containers:
      - name: hn
        image: gcr.io/hackernews-io/github-ivanvanderbyl-ember-hackernews-pwa:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

