apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hackernews-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: hackernews-static-ip
spec:
  backend:
    serviceName: hackernews-production
    servicePort: 8080
